/* ============================================================================
 * immune-data.js * CLAUDEMONZTER - pipeline immune-system feed
 * ----------------------------------------------------------------------------
 * GENERATED by scripts/pipeline-metrics.mjs from the live GitHub API - do NOT
 * hand-edit. Full recompute each run; the file is a pure artifact. Consumed by
 * the immune-system organ page (#318). Schema v1 (#380). All values cumulative
 * or per-story; nothing per-calendar-time. generatedAt is data, not freshness.
 *
 * Attribution footnote: autonomy events are by-account - agentEvents are actions
 * by meta1-monzter (PR opens, commits, comments on pipeline items); humanEvents are
 * JeremyMontz's merges (every merged bot PR - the bot cannot merge), comments, and
 * closes (the bot never closes; it refs). ==========================================================================*/
window.IMMUNE = {
  "schemaVersion": 1,
  "generatedAt": "2026-08-14T09:29:26.154Z",
  "bench": [
    {
      "id": "smoke",
      "issue": 294,
      "title": "Smoke test — proves the runner discovers, executes, and reports a TC.",
      "protects": "Smoke test — proves the runner discovers, executes, and reports a TC."
    },
    {
      "id": "tc-about",
      "issue": 344,
      "title": "About-section — per-type group contract",
      "protects": "About-section — per-type group contract"
    },
    {
      "id": "tc-agent-live",
      "issue": 342,
      "title": "TC — agent-page live layer",
      "protects": "TC — agent-page live layer"
    },
    {
      "id": "tc-articles",
      "issue": 332,
      "title": "Articles — per-type group contract",
      "protects": "Articles — per-type group contract"
    },
    {
      "id": "tc-building-while-i-sleep",
      "issue": 456,
      "title": "tc-building-while-i-sleep — flagship case-study page contract",
      "protects": "Case-study flagship page: CASE STUDY tag, hero GIF, 8-link map, no-em-dash invariant"
    },
    {
      "id": "tc-competency",
      "issue": 333,
      "title": "Competency evidence integrity — data.js",
      "protects": "Competency evidence integrity — data.js"
    },
    {
      "id": "tc-faces-dashboard",
      "issue": 339,
      "title": "TC — faces + dashboard live agent-grid structure",
      "protects": "TC — faces + dashboard live agent-grid structure"
    },
    {
      "id": "tc-github-activity",
      "issue": 364,
      "title": "GitHub activity-feed read-path wiring",
      "protects": "GitHub activity-feed read-path wiring"
    },
    {
      "id": "tc-heart",
      "issue": 338,
      "title": "TC — heart organ + journal page pair",
      "protects": "TC — heart organ + journal page pair"
    },
    {
      "id": "tc-history",
      "issue": 335,
      "title": "Our-History month-graph set — per-type group",
      "protects": "Our-History month-graph set — per-type group"
    },
    {
      "id": "tc-immune-schema",
      "issue": 446,
      "title": "tc-immune-schema — window.IMMUNE v1 validator: single-source extraction + I1–I10 drift rejection",
      "protects": "tc-immune-schema — window.IMMUNE v1 validator: single-source extraction + I1–I10 drift rejection"
    },
    {
      "id": "tc-immune-system",
      "issue": 380,
      "title": "TC — immune system: window.IMMUNE feed + organ-page wiring",
      "protects": "TC — immune system: window.IMMUNE feed + organ-page wiring"
    },
    {
      "id": "tc-index",
      "issue": 340,
      "title": "Homepage — index.html standalone contract",
      "protects": "Homepage — index.html standalone contract"
    },
    {
      "id": "tc-live-display",
      "issue": 336,
      "title": "Live-display read-path wiring",
      "protects": "Live-display read-path wiring"
    },
    {
      "id": "tc-portfolio",
      "issue": 341,
      "title": "Portfolio — portfolio.html standalone contract",
      "protects": "Portfolio — portfolio.html standalone contract"
    },
    {
      "id": "tc-routes",
      "issue": 334,
      "title": "Route validity — data.js reference fields resolve",
      "protects": "Route validity — data.js reference fields resolve"
    },
    {
      "id": "tc-spirit",
      "issue": 337,
      "title": "TC — spirit organ page structure + wiring",
      "protects": "TC — spirit organ page structure + wiring"
    },
    {
      "id": "tc-trackers",
      "issue": 343,
      "title": "TC — house tracker pages structure + wiring",
      "protects": "TC — house tracker pages structure + wiring"
    },
    {
      "id": "tc-webform",
      "issue": 345,
      "title": "TC — data-entry webform WRITE-path wiring",
      "protects": "TC — data-entry webform WRITE-path wiring"
    },
    {
      "id": "tc1-page-chrome",
      "issue": 298,
      "title": "TC1 — Universal page-chrome contract",
      "protects": "TC1 — Universal page-chrome contract"
    },
    {
      "id": "tc2-agent-completeness",
      "issue": 299,
      "title": "TC2 — Agent completeness + roster coherence",
      "protects": "TC2 — Agent completeness + roster coherence"
    },
    {
      "id": "tc3-organ-structural",
      "issue": 300,
      "title": "TC3 — Organ-structural contract (per-type)",
      "protects": "TC3 — Organ-structural contract (per-type)"
    }
  ],
  "counters": {
    "benchSize": 22,
    "storiesShipped": 94,
    "redsCaught": 25,
    "escalations": {
      "specGap": 2,
      "thrashCap": 0,
      "bugFiled": 1
    },
    "verifierEngagements": 8
  },
  "incubation": {
    "built": 12,
    "tested": 30,
    "reviewed": 9
  },
  "autonomy": {
    "agentEvents": 412,
    "humanEvents": 242
  },
  "stories": [
    {
      "issue": 211,
      "lane": "story",
      "rounds": 0,
      "wallClockHours": null,
      "overnight": false
    },
    {
      "issue": 255,
      "lane": "story",
      "rounds": 0,
      "wallClockHours": 0.01,
      "overnight": false
    },
    {
      "issue": 318,
      "lane": "story",
      "rounds": 1,
      "wallClockHours": 0.95,
      "overnight": true
    },
    {
      "issue": 380,
      "lane": "story",
      "rounds": 1,
      "wallClockHours": 0.01,
      "overnight": false
    },
    {
      "issue": 401,
      "lane": "story",
      "rounds": 1,
      "wallClockHours": 0.01,
      "overnight": false
    },
    {
      "issue": 403,
      "lane": "rt",
      "rounds": 0,
      "wallClockHours": 0.01,
      "overnight": false
    },
    {
      "issue": 408,
      "lane": "story",
      "rounds": 2,
      "wallClockHours": 0.07,
      "overnight": false
    },
    {
      "issue": 410,
      "lane": "story",
      "rounds": 1,
      "wallClockHours": 0.01,
      "overnight": false
    },
    {
      "issue": 434,
      "lane": "story",
      "rounds": 1,
      "wallClockHours": 0.01,
      "overnight": true
    },
    {
      "issue": 437,
      "lane": "story",
      "rounds": 0,
      "wallClockHours": 0.01,
      "overnight": false
    },
    {
      "issue": 446,
      "lane": "story",
      "rounds": 0,
      "wallClockHours": 0.01,
      "overnight": true
    },
    {
      "issue": 456,
      "lane": "story",
      "rounds": 1,
      "wallClockHours": 0.01,
      "overnight": true
    }
  ],
  "pulse": [
    {
      "pr": 455,
      "check": "data.js integrity",
      "conclusion": "success"
    },
    {
      "pr": 455,
      "check": "Spellcheck",
      "conclusion": "success"
    },
    {
      "pr": 455,
      "check": "Internal links",
      "conclusion": "success"
    },
    {
      "pr": 455,
      "check": "Contract tests",
      "conclusion": "success"
    },
    {
      "pr": 457,
      "check": "data.js integrity",
      "conclusion": "success"
    },
    {
      "pr": 457,
      "check": "Spellcheck",
      "conclusion": "success"
    },
    {
      "pr": 457,
      "check": "Contract tests",
      "conclusion": "success"
    },
    {
      "pr": 457,
      "check": "Internal links",
      "conclusion": "success"
    },
    {
      "pr": 457,
      "check": "Internal links",
      "conclusion": "success"
    },
    {
      "pr": 457,
      "check": "Spellcheck",
      "conclusion": "success"
    },
    {
      "pr": 457,
      "check": "data.js integrity",
      "conclusion": "success"
    },
    {
      "pr": 457,
      "check": "Contract tests",
      "conclusion": "success"
    },
    {
      "pr": 458,
      "check": "Contract tests",
      "conclusion": "success"
    },
    {
      "pr": 458,
      "check": "data.js integrity",
      "conclusion": "success"
    },
    {
      "pr": 458,
      "check": "Internal links",
      "conclusion": "success"
    },
    {
      "pr": 458,
      "check": "Spellcheck",
      "conclusion": "success"
    },
    {
      "pr": 459,
      "check": "data.js integrity",
      "conclusion": "success"
    },
    {
      "pr": 459,
      "check": "Spellcheck",
      "conclusion": "success"
    },
    {
      "pr": 459,
      "check": "Internal links",
      "conclusion": "success"
    },
    {
      "pr": 459,
      "check": "Contract tests",
      "conclusion": "success"
    }
  ],
  "current": {
    "temperature": "normal",
    "whiteCell": "dormant",
    "blockedIssues": []
  },
  "record": [
    {
      "type": "bug-filed",
      "issue": 353,
      "date": "2026-06-30",
      "title": "about/human.html subnav mount active=\"WRONG\" — must be \"HUMAN\" (tc-about red)"
    },
    {
      "type": "spec-gap",
      "issue": 380,
      "date": "2026-07-07",
      "title": "Immune data feed: pipeline-metrics script + immune-data.js"
    },
    {
      "type": "spec-gap",
      "issue": 446,
      "date": "2026-07-17",
      "title": "Guard the metrics-data immune feed with a window.IMMUNE v1 schema check before publish"
    }
  ]
};
