#!/usr/bin/env node
/**
 * tc-immune-schema — window.IMMUNE v1 validator: single-source extraction + I1–I10 drift rejection  (Tier 1 · standalone · GH #446)
 * ----------------------------------------------------------------------------
 * WHY THIS TC (#446). The live immune feed (immune-data.js) is generated by
 * scripts/pipeline-metrics.mjs and published to the metrics-data branch by the
 * immune-metrics workflow — a push that SKIPS the PR CI gate. So nothing
 * validates the feed's SHAPE before it goes live: tc-immune-system guards the v1
 * schema the PAGE expects (via the committed fixture), but nothing guards what
 * the PIPELINE emits. #446's contract: extract the I1–I10 shape-check into ONE
 * importable validator — a single source of truth for "valid v1" — shared by the
 * fixture test and the workflow, and run it against the freshly generated feed
 * BEFORE publish so a malformed feed can never reach metrics-data.
 *
 * This TC authored from the #446 written contract ONLY. The validator module's
 * SOURCE was NOT read (independence is structural): it is exercised here purely
 * as a black box — inputs in, accept/reject out. The I1–I10 invariants below are
 * lifted from Bond's own prior artifact (tests/tc-immune-system.test.mjs header +
 * checks) and the committed fixture (tests/fixtures/immune-data.sample.js) — both
 * Bond's own bench, reading which is self-consistency, not contamination (#403).
 *
 * CONTRACT (structure / presence / wiring + behavioural shape-domain only):
 *   S1  the extracted validator exists as ONE importable module and exposes a
 *       callable validator (spec item 1: "one importable validator"). The exact
 *       module path + export signature are the implementation's, not the spec's —
 *       resolved here through a documented adaptor. [Confidence: Medium · Inferred]
 *   S2  SINGLE SOURCE (acceptance A3, fixture-test half): the fixture test
 *       tests/tc-immune-system.test.mjs routes its shape-check through the shared
 *       validator (references the extracted module) rather than carrying a
 *       divergent inline copy — otherwise "fixture test and workflow check the
 *       same shape" holds only by hand-sync, which single-sourcing exists to kill.
 *       [Confidence: Medium · Inferred on the module basename; the CONTRACT that
 *       the fixture test consumes the shared validator is spec-mandated (#446 A3).]
 *   B0  the canonical valid v1 fixture (tests/fixtures/immune-data.sample.js) is
 *       ACCEPTED by the validator (proxy for acceptance A1: a valid feed publishes
 *       exactly as today).
 *   B1..B10  a feed breaking exactly ONE of I1–I10 is REJECTED (proxy for
 *       acceptance A2: a feed breaking any I1–I10 invariant fails and is not
 *       pushed). One targeted single-invariant mutation of the valid fixture per
 *       invariant, so each rejection is attributable to that invariant:
 *         I1 non-object IMMUNE · I2 schemaVersion≠1 · I3 non-ISO generatedAt ·
 *         I4 bench-entry shape · I5 counters key/type · I6 autonomy numeric ·
 *         I7 stories lane enum · I8 pulse-entry shape · I9 current temperature
 *         enum · I10 record-entry shape.
 *
 * OUT OF SCOPE (by design):
 *   - The end-to-end WORKFLOW behaviour (feed actually publishes on valid / job
 *     actually fails-and-does-not-push on invalid): that is exercised by CI
 *     running .github/workflows/immune-metrics.yml itself, not statically
 *     decidable in a node contract scan. @ignores below.
 *   - Every feed VALUE (counts, dates, titles) — runtime data, never contract
 *     (global editorial default, #403); this TC asserts value TYPES / enum
 *     DOMAINS / key presence only, exactly as tc-immune-system does.
 *   - The validator's internal implementation, error-message wording, and the
 *     CLI wrapper's argv shape — implementation, not contract.
 *
 * TEETH: if the extracted validator drifts from the v1 schema — fails to reject a
 * dropped section, a bad enum token, a schemaVersion bump, or a removed entry key
 * — a malformed feed would publish uncaught; that gap reds HERE. If the fixture
 * test stops sharing the validator (S2), the "single source of truth" the story
 * bought silently decays back into two hand-synced copies; that reds here too.
 *
 * Zero-dep (node stdlib only); dynamic import() of the validator module; exit 1 on
 * any failure via the shared _assert reporter. Run directly or via tests/run.mjs.
 *
 * @covers: scripts/immune-schema.mjs (window.IMMUNE v1 validator — single source)
 * @ignores: end-to-end workflow publish/fail behaviour — runtime (CI runs the workflow) / Tier 4
 * @ignores: feed values (counts, dates, titles) — editorial / runtime data
 * @ignores: validator internals + error-message wording + CLI argv shape — implementation
 */
import { readFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';
import { makeReport } from './_assert.mjs';

const ROOT = process.cwd();
const rd = (p) => readFileSync(join(ROOT, p), 'utf8');
const r = makeReport('tc-immune-schema');

// The extracted validator's home. The #446 spec names the generator
// (scripts/pipeline-metrics.mjs) but NOT the validator module, so its path is
// inferred as a sibling in scripts/. [Confidence: Medium · Inferred]
const VALIDATOR = 'scripts/immune-schema.mjs';
// Bond's own prior artifact — the fixture test that must share the validator (S2).
const FIXTURE_TEST = 'tests/tc-immune-system.test.mjs';
// Bond's canonical valid v1 fixture — the accept case + the mutation base.
const FIXTURE = 'tests/fixtures/immune-data.sample.js';

// ---------------------------------------------------------------------------
// Load Bond's own valid fixture object (house loadWindow pattern).
// ---------------------------------------------------------------------------
function loadWindow(path) { const win = {}; new Function('window', rd(path))(win); return win; }
const VALID = loadWindow(FIXTURE).IMMUNE;              // canonical valid window.IMMUNE
const clone = (o) => JSON.parse(JSON.stringify(o));    // fixture is JSON-safe
const broken = (mutate) => { const c = clone(VALID); mutate(c); return c; };

// ---------------------------------------------------------------------------
// Inferred-interface adaptor. The spec guarantees an importable validator but
// not its signature, so bind to whatever standard shape the implementation used
// WITHOUT reading its source: pick the first callable among common export names,
// and read its verdict across the common return/throw conventions. Permissive in
// HOW a verdict is read; SHARP in WHAT is asserted (accept-valid / reject-each).
// [Confidence: Medium · Inferred]
// ---------------------------------------------------------------------------
function resolveValidator(mod) {
  const named = ['validateImmuneV1', 'validateImmune', 'validateFeed', 'validate',
    'isValidImmuneV1', 'isValidImmune', 'check', 'checkImmune', 'assertImmuneV1'];
  const cands = [mod?.default, ...named.map((n) => mod?.[n])];
  for (const c of cands) if (typeof c === 'function') return c;
  for (const v of Object.values(mod || {})) if (typeof v === 'function') return v; // last resort
  return null;
}

// Returns 'accept' | 'reject'. Handles: throw-on-invalid; boolean; {valid}/{ok};
// errors array; {errors:[...]}; truthy/undefined-no-throw => accept.
function verdict(fn, input) {
  let ret, threw = false;
  try { ret = fn(input); } catch { threw = true; }
  if (threw) return 'reject';
  if (ret === false) return 'reject';
  if (ret && typeof ret === 'object') {
    if ('valid' in ret) return ret.valid ? 'accept' : 'reject';
    if ('ok' in ret) return ret.ok ? 'accept' : 'reject';
    if (Array.isArray(ret)) return ret.length === 0 ? 'accept' : 'reject';
    if (Array.isArray(ret.errors)) return ret.errors.length === 0 ? 'accept' : 'reject';
  }
  return 'accept'; // true / undefined / null / other truthy scalar, no throw
}

// ---------------------------------------------------------------------------
// S1 — the validator exists as one importable module exposing a callable.
// ---------------------------------------------------------------------------
let validate = null;
if (!existsSync(join(ROOT, VALIDATOR))) {
  r.check(false, `${VALIDATOR} does not exist — spec item 1 requires one importable v1 validator`);
} else {
  try {
    const mod = await import(pathToFileURL(join(ROOT, VALIDATOR)).href);
    validate = resolveValidator(mod);
    r.check(typeof validate === 'function',
      `${VALIDATOR} exposes no callable validator export (checked default + common names)`);
  } catch (e) {
    r.check(false, `${VALIDATOR} failed to import — ${e.message}`);
  }
}

// ---------------------------------------------------------------------------
// S2 — single source: the fixture test routes through the shared validator.
// ---------------------------------------------------------------------------
if (existsSync(join(ROOT, FIXTURE_TEST))) {
  const src = rd(FIXTURE_TEST);
  r.check(/immune-schema/.test(src),
    `${FIXTURE_TEST} does not reference the shared validator (immune-schema) — ` +
    `single source of truth (A3) requires the fixture test to check the SAME shape via the extracted validator`);
} else {
  r.check(false, `${FIXTURE_TEST} not found — cannot verify single-sourcing`);
}

// ---------------------------------------------------------------------------
// B0 — the canonical valid fixture is ACCEPTED.
// B1..B10 — each single-invariant mutation is REJECTED.
// (Only run if a validator was resolved; otherwise S1 already recorded the fail
// and running these would just add noise.)
// ---------------------------------------------------------------------------
if (typeof validate === 'function') {
  r.check(verdict(validate, clone(VALID)) === 'accept',
    'B0: the canonical valid v1 fixture was NOT accepted by the validator');

  const cases = [
    ['I1 non-object IMMUNE', null],
    ['I2 schemaVersion !== 1', broken((c) => { c.schemaVersion = 2; })],
    ['I3 non-ISO generatedAt', broken((c) => { c.generatedAt = 'not-a-date'; })],
    ['I4 bench entry missing a key', broken((c) => { delete c.bench[0].protects; })],
    ['I5 counters missing a numeric key', broken((c) => { delete c.counters.redsCaught; })],
    ['I6 autonomy field non-numeric', broken((c) => { c.autonomy.agentEvents = 'lots'; })],
    ['I7 stories lane out of enum', broken((c) => { c.stories[0].lane = 'backlog'; })],
    ['I8 pulse entry missing a key', broken((c) => { delete c.pulse[0].conclusion; })],
    ['I9 current.temperature out of enum', broken((c) => { c.current.temperature = 'boiling'; })],
    ['I10 record entry missing a key', broken((c) => { delete c.record[0].date; })],
  ];
  for (const [label, bad] of cases) {
    r.check(verdict(validate, bad) === 'reject',
      `B(${label}): a feed breaking ${label} was NOT rejected — drift class would publish uncaught`);
  }
}

r.done('immune-schema: single-source v1 validator (S1/S2) + accept-valid/reject-I1–I10 drift (B0–B10) checked');
