// tests/fixtures/immune-data.sample.js
// -----------------------------------------------------------------------------
// Committed v1 window.IMMUNE fixture for tc-immune-system (I1–I10).
//
// The live feed is generated by scripts/pipeline-metrics.mjs and, since #437,
// published to the metrics-data branch (loaded by graph/immune.html via jsdelivr)
// — it is NO LONGER committed to main. This fixture is a stable, minimal stand-in
// so the schema contract stays enforced against a fixed shape rather than a file
// that changes every pipeline run.
//
// The TC asserts SHAPE ONLY — keys present, value TYPES, and the spec enum
// domains (schemaVersion, lane, temperature, whiteCell). The numbers/strings
// below are illustrative and are never asserted. Keep this in sync with the
// window.IMMUNE v1 schema if it evolves.
window.IMMUNE = {
  schemaVersion: 1,
  generatedAt: "2026-07-15T08:17:00Z",
  bench: [
    { id: "tc-immune-system", issue: 380, title: "Immune system page + feed", protects: "graph/immune.html" }
  ],
  counters: {
    benchSize: 19,
    storiesShipped: 42,
    redsCaught: 7,
    verifierEngagements: 3,
    escalations: { specGap: 1, thrashCap: 0, bugFiled: 2 }
  },
  autonomy: { agentEvents: 128, humanEvents: 34 },
  stories: [
    { issue: 442, lane: "story", rounds: 2, wallClockHours: 5.5, overnight: false }
  ],
  pulse: [
    { pr: 442, check: "Contract tests", conclusion: "failure" }
  ],
  current: { temperature: "normal", whiteCell: "dormant", blockedIssues: [] },
  record: [
    { type: "Story", issue: 437, date: "2026-07-14", title: "Immune feed — event-driven regen workflow + page repoint" }
  ]
};
